name: Run Multiple Python Files

on: [push, pull_request]

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # Updated to v4 for Node.js 20 support

    - name: Set up Python
      uses: actions/setup-python@v4  # Updated to v4 for Node.js 20 support
      with:
        python-version: '3.x'

    
    - name: Run multiple Python scripts
      run: |
        python .github/workflows/Question1.py
        python .github/workflows/Question2.py
        python .github/workflows/Question3.py
        python .github/workflows/Question4.py
        python .github/workflows/Question5.py
        python .github/workflows/Question6.py
